package com.lb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AUTH.
 */
public class Auth {

    private Long id;
    private int user_id;
    private String token;

    public Auth() {
    }

    public Auth(Long id) {
        this.id = id;
    }

    public Auth(Long id, int user_id, String token) {
        this.id = id;
        this.user_id = user_id;
        this.token = token;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

}
