package com.lb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lb.Auth;

import com.lb.AuthDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig authDaoConfig;

    private final AuthDao authDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        authDaoConfig = daoConfigMap.get(AuthDao.class).clone();
        authDaoConfig.initIdentityScope(type);

        authDao = new AuthDao(authDaoConfig, this);

        registerDao(Auth.class, authDao);
    }
    
    public void clear() {
        authDaoConfig.getIdentityScope().clear();
    }

    public AuthDao getAuthDao() {
        return authDao;
    }

}
